trigger:
  batch: true
  branches:
    include:
      - master
      - feature/*
      - fix/*

pr: none

resources:
  repositories:
    - repository: pipeline-library
      type: github
      endpoint: quantum-sec-github
      name: quantum-sec/pipeline-library

jobs:
  - template: templates/jobs/default.yml@pipeline-library
    parameters:
      containerImage: quantumci.azurecr.io/quantum-ci-terragrunt:latest
      deploySteps:
        - template: templates/steps/versioning/update-source-reference.yml@pipeline-library
          parameters:
            name: UpdateInfrastructureModules
            displayName: Update Infrastructure Modules
            srcRepository: package-cloudflare.git
            dstRepository: infrastructure-modules
            condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.Reason'], 'PullRequest')))
